---
title: "Diabetes in MHHS"
subtitle: "Results for January 2018"
author: "Brian Gulbis, PharmD, BCPS"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html")
```

```{r, message=FALSE}
library(tidyverse)
library(plotly)
library(kableExtra)

x <- dirr::get_rds("../data/tidy/2018-01")
plot_col <- "#cccccc"

facilities <- c(
    "HERMANN" = "Texas Med Ctr",
    "CYPRESS" = "Cypress",
    "PEARLAND" = "Pearland",
    "Woodland" = "Woodlands"
)

dm_patients <- data_patients_dm %>%
    mutate_at("facility", str_replace_all, pattern = facilities) %>%
    mutate_at("facility", str_replace_all, pattern = "^.. ", replacement = "")

all_inpatients <- data_inpatients %>%
    mutate_at("facility", str_replace_all, pattern = facilities) %>%
    mutate_at("facility", str_replace_all, pattern = "^.. ", replacement = "")

```

```{r, fig.cap="Number of patients with any ICD-10-CM code for diabetes during an encounter at each facility. Data for each facility are split into type of visit (inpatient, emergency, or observation)."}
encounter_types <- c("Inpatient", "Emergency", "Observation")

count_facility <- dm_patients %>%
    filter(visit.type %in% encounter_types) %>%
    count(facility, sort = TRUE) %>%
    rename(n_pts = n)

dm_patients %>%
    filter(visit.type %in% encounter_types) %>%
    count(facility, visit.type, sort = TRUE) %>%
    left_join(count_facility, by = "facility") %>%
    arrange(desc(n_pts), desc(n)) %>%
    mutate_at("visit.type", factor, levels = encounter_types) %>%
    mutate_at("facility", as_factor) %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_bars(x = ~n, y = ~facility, color = ~visit.type) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Patients", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE,
            showline = FALSE, 
            linecolor = plot_col
        ),
        margin = list(l = 150))
```

```{r fig.cap="Number of admitted patients with each category of diabetes by facility."}
count_facility_inpt <- dm_patients %>%
    filter(visit.type == "Inpatient") %>%
    count(facility, sort = TRUE) %>%
    rename(n_pts = n)

dm_patients %>%
    filter(visit.type == "Inpatient") %>%
    select(millennium.id, facility) %>%
    left_join(data_dm_diagnosis, by = "millennium.id") %>%
    count(facility, dm_type, sort = TRUE) %>%
    left_join(count_facility_inpt, by = "facility") %>%
    arrange(desc(n_pts), desc(n)) %>%
    mutate_at(c("facility", "dm_type"), as_factor) %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_bars(x = ~n, y = ~facility, color = ~dm_type) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Patients", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE,
            showline = FALSE, 
            linecolor = plot_col
        ),
        margin = list(l = 150))
```

```{r}
count_all <- all_inpatients %>%
    count(facility) %>%
    rename(n_all = n)

count_dm <- dm_patients %>%
    filter(visit.type == "Inpatient") %>%
    count(facility) %>%
    left_join(count_all, by = "facility") %>%
    mutate(pct_dm = n / n_all * 100) %>%
    arrange(desc(pct_dm)) %>%
    mutate_at("facility", as_factor) 

count_dm_mhhs <- count_dm %>%
    summarize_at(c("n", "n_all"), sum, na.rm = TRUE) %>%
    mutate(
        facility = "MHHS Combined",
        pct_dm = n / n_all * 100
    ) %>%
    select(facility, everything())
```

```{r, fig.cap="Percent of admitted patients with diabetes at each facility. The size of the dot corresponds to the total number of inpatients at each facility. The vertical line indicates the percent of diabetes patients from all MHHS facilities combined."}
count_dm %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_markers(x = ~pct_dm, y = ~facility, size = ~n_all) %>%
    # add_lines(data = count_dm_mhhs, )
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Patients (%)", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col
        ),
        margin = list(l = 150),
        shapes = list(
            type = "line", 
            x0 = count_dm_mhhs$pct_dm, 
            x1 = count_dm_mhhs$pct_dm, 
            y0 = 0, 
            y1 = 11,
            line = list(color = plot_col)
        )
    )
```

```{r}
count_dm %>%
    mutate(
        annual_n = (n_all / 4) * 12,
        annaul_dm = (n / 4) * 12
    ) %>%
    select(
        Facility = facility, 
        `Number of Patients` = annual_n, 
        `Number with Diabetes` = annaul_dm, 
        `Patients with Diabetes (%)` = pct_dm
    ) %>%
    knitr::kable(
        digits = 0, 
        caption = "Admitted patients with diabetes at each facility"
    ) %>%
    kable_styling(full_width = FALSE)
```

### Hemoglobin A1c

```{r, fig.cap="Percent of patients with a hemoglobin A1c > 8% at each facility."}
df_a1c <- dm_patients %>%
    filter(visit.type == "Inpatient") %>%
    select(millennium.id, facility) %>%
    left_join(data_a1c, by = "millennium.id") 

count_a1c <- count(df_a1c, facility)

df_a1c %>%
    group_by(facility) %>%
    summarize_at("high_a1c", sum, na.rm = TRUE) %>%
    left_join(count_a1c, by = "facility") %>%
    mutate_at("pct_high_a1c", funs(high_a1c / n * 100)) %>%
    arrange(desc(pct_high_a1c)) %>%
    mutate_at("facility", as_factor) %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_bars(x = ~pct_high_a1c, y = ~facility) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Patients (%)", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE,
            showline = FALSE, 
            linecolor = plot_col
        ),
        margin = list(l = 150))

```

```{r, fig.cap="Distribution of A1c values at each facility."}
median_a1c <- df_a1c %>%
    group_by(facility) %>%
    summarize_at("lab.result", median, na.rm = TRUE) %>%
    arrange(desc(lab.result)) %>%
    mutate_at("facility", as_factor)

df_a1c %>%
    filter(!is.na(lab.result)) %>%
    mutate_at("facility", factor, levels = median_a1c$facility) %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_boxplot(x = ~lab.result, y = ~facility) %>%
    layout(
        xaxis = list(
            title = "A1c (%)", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE,
            showline = TRUE, 
            linecolor = plot_col
        ),
        margin = list(l = 150))

```

### Comorbidities

```{r, fig.cap="Percent of patients with 2 or more comorbidities at each facility."}
df_comorbidities <- dm_patients %>%
    filter(visit.type == "Inpatient") %>%
    select(millennium.id, facility) %>%
    left_join(data_comorbidities, by = "millennium.id") %>%
    rowwise() %>%
    mutate(
        num_comorb = sum(CHF, HTN, Pulmonary, HL, CAD, na.rm = TRUE),
        high_comorb = num_comorb > 1
    ) %>%
    ungroup()

df_comorbidities %>%
    group_by(facility) %>%
    summarize_at("high_comorb", sum, na.rm = TRUE) %>%
    left_join(count_facility_inpt, by = "facility") %>%
    mutate_at("pct_pts", funs(high_comorb / n_pts * 100)) %>%
    arrange(desc(pct_pts)) %>%
    mutate_at("facility", as_factor) %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_bars(x = ~pct_pts, y = ~facility) %>%
    layout(
        xaxis = list(
            title = "Patients (%)", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE,
            showline = FALSE, 
            linecolor = plot_col
        ),
        margin = list(l = 150))
```


```{r, fig.cap="Percent of patients with each comorbidity at each facility."}
dm_patients %>%
    filter(visit.type == "Inpatient") %>%
    select(millennium.id, facility) %>%
    left_join(data_comorbidities, by = "millennium.id") %>%
    group_by(facility) %>%
    summarize_if(is.logical, sum, na.rm = TRUE) %>%
    left_join(count_facility_inpt, by = "facility") %>%
    mutate_at(
        c("CHF", "HTN", "Pulmonary", "HL", "CAD"), 
        funs(. / n_pts * 100)
    ) %>%
    gather(comorbidity, pct_pts, CHF:CAD) %>%
    arrange(desc(n_pts)) %>%
    mutate_at("facility", as_factor) %>%
    mutate_at("facility", fct_rev) %>%
    plot_ly() %>%
    add_bars(x = ~pct_pts, y = ~facility, color = ~comorbidity) %>%
    layout(
        xaxis = list(
            title = "Patients (%)", 
            showgrid = FALSE, 
            showline = TRUE, 
            linecolor = plot_col, 
            ticks = "outside",
            tickcolor = plot_col
        ),
        yaxis = list(
            title = "Facility", 
            showgrid = FALSE,
            showline = FALSE, 
            linecolor = plot_col
        ),
        margin = list(l = 150))
```

